### ISSUE TITLE
English

### ISSUE THREAD

**Issue by toxa9** [zhitkur/SSIBAL#1]
Hey! 
Could you rewrite the comments in the code into English?

**Comment by zhitkur** [comment]
Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On 2021년 March 6일 Saturday PM 8:48, Anton Solonnikov <notifications@github.com> wrote:

Hello. First of all, it's an honor to see my code. I'm not good at English, so I use a translator, but I'll revise what you requested as soon as possible.

**Comment by toxa9** [comment]
Thanks in advance, that would be great.

**Comment by zhitkur** [comment]
Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
On 2021년 March 6일 Saturday PM 11:38, Anton Solonnikov <notifications@github.com> wrote:

I translated what I thought was important, but if you have any questions, feel free to ask.

**Comment by toxa9** [comment]
Thank you so much!
